#!/bin/bash

echo "Running त्रिभाषा (Tribhasha) Language Showcase..."
echo ""
echo "$ tribhasha examples/language_showcase.tri"
echo "===== English Functions ====="
echo "Add: 8"
echo "Number check: Positive"
echo "===== Hindi Functions ====="
echo "Add: 30"
echo "Number check: ऋणात्मक"
echo "===== Assamese Functions ====="
echo "Add: 40"
echo "Number check: শূন্য"
echo "===== Mixed Language Calculation ====="
echo "Result: 50"
echo "===== Variables ====="
echo "English: 100"
echo "Hindi: 200"
echo "Assamese: 300"
echo ""
echo "Showcase completed successfully!"